// <auto-generated />
namespace Acco.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class faranAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(faranAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202304152029385_faranAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
